import { AppConfig } from '../../conf'

export const mapMeta = {
    India: {
        name: 'India',
        geoDataFile: `${AppConfig.baseTopo}/india.json`,
        mapType: 'COUNTRY',
        graphObjectName: 'india',
    },
    'Andaman and Nicobar Islands': {
        name: 'Andaman and Nicobar Islands',
        geoDataFile: `${AppConfig.baseTopo}/andamannicobarislands.json`,
        mapType: 'STATE',
        graphObjectName: 'andamannicobarislands_district',
    },
    'Arunachal Pradesh': {
        name: 'Arunachal Pradesh',
        geoDataFile: `${AppConfig.baseTopo}/arunachalpradesh.json`,
        mapType: 'STATE',
        graphObjectName: 'arunachalpradesh_district',
    },
    'Andhra Pradesh': {
        name: 'Andhra Pradesh',
        geoDataFile: `${AppConfig.baseTopo}/andhrapradesh.json`,
        mapType: 'STATE',
        graphObjectName: 'andhrapradesh_district',
    },
    Assam: {
        name: 'Assam',
        geoDataFile: `${AppConfig.baseTopo}/assam.json`,
        mapType: 'STATE',
        graphObjectName: 'assam_district',
    },
    Bihar: {
        name: 'Bihar',
        geoDataFile: `${AppConfig.baseTopo}/bihar.json`,
        mapType: 'STATE',
        graphObjectName: 'bihar_district',
    },
    Chhattisgarh: {
        name: 'Chhattisgarh',
        geoDataFile: `${AppConfig.baseTopo}/chhattisgarh.json`,
        mapType: 'STATE',
        graphObjectName: 'chhattisgarh_district',
    },
    Delhi: {
        name: 'Delhi',
        geoDataFile: `${AppConfig.baseTopo}/delhi.json`,
        mapType: 'STATE',
        graphObjectName: 'delhi_1997-2012_district',
    },
    Karnataka: {
        name: 'Karnataka',
        geoDataFile: `${AppConfig.baseTopo}/karnataka.json`,
        mapType: 'STATE',
        graphObjectName: 'karnataka_district',
    },
    Kerala: {
        name: 'Kerala',
        geoDataFile: `${AppConfig.baseTopo}/kerala.json`,
        mapType: 'STATE',
        graphObjectName: 'kerala_district',
    },
    Goa: {
        name: 'Goa',
        geoDataFile: `${AppConfig.baseTopo}/goa.json`,
        mapType: 'STATE',
        graphObjectName: 'goa_district',
    },
    Gujarat: {
        name: 'Gujarat',
        geoDataFile: `${AppConfig.baseTopo}/gujarat.json`,
        mapType: 'STATE',
        graphObjectName: 'gujarat_district_2011',
    },
    Haryana: {
        name: 'Haryana',
        geoDataFile: `${AppConfig.baseTopo}/haryana.json`,
        mapType: 'STATE',
        graphObjectName: 'haryana_district',
    },
    'Himachal Pradesh': {
        name: 'Himachal Pradesh',
        geoDataFile: `${AppConfig.baseTopo}/himachalpradesh.json`,
        mapType: 'STATE',
        graphObjectName: 'himachalpradesh_district',
    },
    'Jammu and Kashmir': {
        name: 'Jammu and Kashmir',
        geoDataFile: `${AppConfig.baseTopo}/jammukashmir.json`,
        mapType: 'STATE',
        graphObjectName: 'jammukashmir_district',
    },
    Jharkhand: {
        name: 'Jharkhand',
        geoDataFile: `${AppConfig.baseTopo}/jharkhand.json`,
        mapType: 'STATE',
        graphObjectName: 'jharkhand_district',
    },
    Ladakh: {
        name: 'Ladakh',
        geoDataFile: `${AppConfig.baseTopo}/ladakh.json`,
        mapType: 'STATE',
        graphObjectName: 'ladakh_district',
    },
    'Madhya Pradesh': {
        name: 'Madhya Pradesh',
        geoDataFile: `${AppConfig.baseTopo}/madhyapradesh.json`,
        mapType: 'STATE',
        graphObjectName: 'madhyapradesh_district',
    },
    Maharashtra: {
        name: 'Maharashtra',
        geoDataFile: `${AppConfig.baseTopo}/maharashtra.json`,
        mapType: 'STATE',
        graphObjectName: 'maharashtra_district',
    },
    Manipur: {
        name: 'Manipur',
        geoDataFile: `${AppConfig.baseTopo}/manipur.json`,
        mapType: 'STATE',
        graphObjectName: 'manipur_pre2016_districts',
    },
    Meghalaya: {
        name: 'Meghalaya',
        geoDataFile: `${AppConfig.baseTopo}/meghalaya.json`,
        mapType: 'STATE',
        graphObjectName: 'meghalaya_district',
    },
    Mizoram: {
        name: 'Mizoram',
        geoDataFile: `${AppConfig.baseTopo}/mizoram.json`,
        mapType: 'STATE',
        graphObjectName: 'mizoram_district',
    },
    Nagaland: {
        name: 'Nagaland',
        geoDataFile: `${AppConfig.baseTopo}/nagaland.json`,
        mapType: 'STATE',
        graphObjectName: 'nagaland_district',
    },
    Odisha: {
        name: 'Odisha',
        geoDataFile: `${AppConfig.baseTopo}/odisha.json`,
        mapType: 'STATE',
        graphObjectName: 'odisha_district',
    },
    Punjab: {
        name: 'Punjab',
        geoDataFile: `${AppConfig.baseTopo}/punjab.json`,
        mapType: 'STATE',
        graphObjectName: 'punjab_district',
    },
    Rajasthan: {
        name: 'Rajasthan',
        geoDataFile: `${AppConfig.baseTopo}/rajasthan.json`,
        mapType: 'STATE',
        graphObjectName: 'rajasthan_district',
    },
    Sikkim: {
        name: 'Sikkim',
        geoDataFile: `${AppConfig.baseTopo}/sikkim.json`,
        mapType: 'STATE',
        graphObjectName: 'sikkim_district',
    },
    'Tamil Nadu': {
        name: 'Tamil Nadu',
        geoDataFile: `${AppConfig.baseTopo}/tamil-nadu.json`,
        mapType: 'STATE',
        graphObjectName: 'tamilnadu_district',
    },
    Telangana: {
        name: 'Telangana',
        geoDataFile: `${AppConfig.baseTopo}/telugana.json`,
        mapType: 'STATE',
        graphObjectName: 'telugana',
    },
    Tripura: {
        name: 'Tripura',
        geoDataFile: `${AppConfig.baseTopo}/tripura.json`,
        mapType: 'STATE',
        graphObjectName: 'tripura_district',
    },
    Uttarakhand: {
        name: 'Uttarakhand',
        geoDataFile: `${AppConfig.baseTopo}/uttarakhand.json`,
        mapType: 'STATE',
        graphObjectName: 'uttarakhand_district',
    },
    'Uttar Pradesh': {
        name: 'Uttar Pradesh',
        geoDataFile: `${AppConfig.baseTopo}/uttarpradesh.json`,
        mapType: 'STATE',
        graphObjectName: 'uttarpradesh_district',
    },

    'West Bengal': {
        name: 'West Bengal',
        geoDataFile: `${AppConfig.baseTopo}/westbengal.json`,
        mapType: 'STATE',
        graphObjectName: 'westbengal_district',
    },
};
